spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1427
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  token:
    secret:
      expiry: 604800000
      key: SGkuIFRoaXMgaXMgc2VjcmV0IGtleSBmb3IgSldUIGZyb20gdHJhbnNhY3Rpb24tcmVwb3J0cyBwcm9qZWN0LiBCeTogZWVzbGFtYmVj
notion:
  api-url: https://api.notion.com
  api-version: 2022-06-28
  database-id: 1777733443f88012b75ef60cc23d154b
  auth-token: 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
