spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1427
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
