package uz.pdp.transactionreports.utils.enums;

public enum UserState {
    DEFAULT,
    AUTHENTICATED,
    ENTER_USERNAME,
    ENTER_PASSWORD,
    ENTER_PERIOD,
    ENTER_EXPENSE_CATEGORY,
    ENTER_CUSTOMER_PHONE_NUMBER,
    ENTER_SERVICE_NAME,
    ENTER_NEW_USERNAME,
    ENTER_NEW_PASSWORD,
    ENTER_NEW_NAME,
}
